##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 2005  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
##
## Project: IDEA
##    File: \n4_servers3\pkg\MrServers\MrVista\Ice\IceIdeaFunctors\IceTEMPL4TE\makefile.trs
## Version:
##  Author: 
##    Date: 
##
##    Lang: make
##
## Descrip: Makefile fuer Target IceTemplate
##
##-----------------------------------------------------------------------------

##-----------------------------------------------------------------------------
## Naehere Informationen zum den moeglichen Macros im Makefile siehe
## MedMake-Dokumentation Q:/csw/MedMake/html/contents_t6.html
##

##-----------------------------------------------------------------------------
## enter NLS library
##

##-----------------------------------------------------------------------------
## enter local compiler flags
##

##-----------------------------------------------------------------------------
## enter include paths
##
CPPFLAGS(-DICEIDEAFUNCTORS_EXPORTS)
CPPFLAGS(-DICE_NAMESPACE=IceTEMPL4TE)
CPPFLAGS(-D_VX_VERSION_VE)

##-----------------------------------------------------------------------------
## enter source files
##
CPPSOURCES(Functor_TEMPL4TE_PostProcessing)
CPPSOURCES(TEMPL4TE_Configurator)
CPPSOURCES(TEMPL4TE_ObjectMap)
CPPSOURCES(XFunctor)

##-----------------------------------------------------------------------------
## enter local linker flags
##

##-----------------------------------------------------------------------------
## enter link libraries
##
LDLIBS(IceAlgos)
LDLIBS(IceBasic)
LDLIBS(IceUtils)
LDLIBS(MrParc)
LDLIBS(UTrace)

# StdExcept
MSDEV_i586_WinNT400(LDLIBS(MrClassDump))

##-----------------------------------------------------------------------------
## enter target name
##
LIB(IceTEMPL4TE)
EVPTLB(IceTEMPL4TE)

##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 2005  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------

VISTA_GCC_LINUX_AMD64(LDLIBS(stlport))  
VISTA_GCC_LINUX_AMD64(LDLIBS(ace)) 

